name: Test RCD

on:
  push

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.8"
    - name: Install system deps
      run: |
        sudo apt update
        sudo apt install -y build-essential \
                 libxml2 \
                 libxml2-dev \
                 zlib1g-dev \
                 python3-tk \
                 graphviz
    - name: Install python deps
      run: |
        python3.8 -m venv env
        source env/bin/activate
        pip install -U pip
        pip install -r requirements.txt
    - name: link
      run: |
        ln -fs $pwd/pyAgrum/lib/image.py $pwd/env/lib/python3.8/site-packages/pyAgrum/lib/
        ln -fs $pwd/causallearn/search/ConstraintBased/FCI.py $pwd/env/lib/python3.8/site-packages/causallearn/search/ConstraintBased/
        ln -fs $pwd/causallearn/utils/Fas.py $pwd/env/lib/python3.8/site-packages/causallearn/utils/
        ln -fs $pwd/causallearn/utils/PCUtils/SkeletonDiscovery.py $pwd/env/lib/python3.8/site-packages/causallearn/utils/PCUtils/
        ln -fs $pwd/causallearn/graph/GraphClass.py $pwd/env/lib/python3.8/site-packages/causallearn/graph/
    - name: gen data
      run: |
        source env/bin/activate
        python gen_data.py
    - name: run rcd with k=3
      run: python rcd.py --path data/s-2/n-10-d-3-an-1-nor-s-1000-an-s-1000 --local --k 3
    - name: run rcd with k=2
      run: python rcd.py --path data/s-2/n-10-d-3-an-1-nor-s-1000-an-s-1000 --local --k 2
    - name: run rcd with k=1
      run: python rcd.py --path data/s-2/n-10-d-3-an-1-nor-s-1000-an-s-1000 --local --k 1
        
        
